In [1]:
import torch

In [2]:
a=torch.tensor(5.)
a.shape

torch.Size([])

In [8]:
b=torch.tensor([[2,3,5],
             [2,9,5]])
b.shape

torch.Size([2, 3])

In [27]:
# check derivatives
x= torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(5., requires_grad=True)

In [32]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [41]:
y.backward()  #backward important for differentiation

In [44]:
print("dy/df", b.grad)

dy/df tensor(1.)


In [35]:
import numpy as np


In [39]:
array = np.array([[1,3],
                [4,5]])
array.shape

(2, 2)

In [40]:
# convert numpy to tensors
a = torch.from_numpy(array)
a.shape

torch.Size([2, 2])

In [25]:
a=torch.zeros([1,3,4,4])
a
# a = torch.ones([0,2,4,4])
# a.shape

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [23]:
print(a.shape)
print(a.device)
print(a.dtype)

torch.Size([2, 3, 4, 4])
cpu
torch.float32


In [27]:
tensor = torch.tensor([[3,3],[2,4]])
tensor

tensor([[3, 3],
        [2, 4]])

In [29]:
#joining tensors
torch.cat([tensor,tensor,tensor])

tensor([[3, 3],
        [2, 4],
        [3, 3],
        [2, 4],
        [3, 3],
        [2, 4]])

In [73]:
z= tensor.mul(tensor)
z

tensor([[ 9,  9],
        [ 4, 16]])

In [74]:
z= tensor * tensor
z

tensor([[ 9,  9],
        [ 4, 16]])

In [78]:
t= torch.ones(5)
print(t.shape)
n=t.numpy()
print(n.shape)

torch.Size([5])
(5,)


In [30]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Transfer Learning

In [81]:
from torchvision import models

In [ ]:
model =models.vgg16(pretrained=True)